pod 'Stripe'
pod 'JSQFlatButton'
pod 'FlatUIKit'
pod 'Parse'
pod 'LTPhoneNumberField'
pod 'TSCurrencyTextField', '~> 0.1.0'
pod 'JDFCurrencyTextField'
pod 'CardIO'
pod 'FXBlurView'
pod 'SWTableViewCell'